Add better code check and pre-commit hook
3rdparty/dev-tools pull request #75
Opened 2023-05-05 13:43 UTC by while-false

This PR changes how we do code style checks locally. It is the first step towards better code checking on our code spaces and on our Github Actions.

2023-05-05 16:27 UTC, rjhuijsman requested changes

2023-05-05 16:27 UTC, rjhuijsman commented on check-line-length
> +    from multiprocessing import Pool
We usually keep all of our imports at the top of the file, no?

2023-05-05 16:27 UTC, rjhuijsman commented on check-style
> +run_check() {
This file could use a comment explaining how to use it, most notably the expected arguments and what it does with them. It seems like we're supposed to pass a program to run?

2023-05-05 16:27 UTC, rjhuijsman commented on pre-commit
> +# Run the check-style script from dev-tools as pre-commit hook.
Are you confident it's safe to drop the logic that finds the root of the git repository to run the checks there?

2023-05-05 16:36 UTC, benh commented
Hi all, let's drop this PR for now and revisit it in the future after we've focused on step one which is getting the precommit hook to be doing all of the things that the GitHub action is doing!

2023-05-10 10:53 UTC, while-false commented
Closing in favour of https://github.com/3rdparty/dev-tools/pull/77

2023-05-10 10:53 UTC, closed without merging